export interface City {
  id: string
  name: string
  country: string
  latitude: number
  longitude: number
  icao: string
  timezone: string
  /** UTC offset in minutes (positive = east). Used for timezone sorting. */
  utcOffsetMinutes: number
  description: string
  gradient: string
  image: string
  /** Webcam slots: image URL (string), iframe, video stream, or external link */
  webcams?: Array<
    | string
    | { type: 'iframe'; url: string }
    | { type: 'video'; url: string; poster?: string }
    | { type: 'link'; url: string; poster?: string }
  >
  moji?: string
}

export const CITIES: City[] = [
  {
    id: 'sao-paulo',
    name: 'Sao Paulo',
    country: 'Brazil',
    latitude: -23.55,
    longitude: -46.63,
    icao: 'SBGR',
    timezone: 'America/Sao_Paulo',
    utcOffsetMinutes: -180,
    description: 'The largest city in the Southern Hemisphere, a vibrant metropolis of culture and commerce.',
    gradient: 'from-amber-600 via-orange-500 to-rose-500',
    image: '/images/cities/sao-paulo.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1249392511/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1356224219/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1580415336/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1356224219/original.jpg'
    ]
  },
  {
    id: 'nyc',
    name: 'New York City',
    country: 'USA',
    latitude: 40.71,
    longitude: -74.01,
    icao: 'KJFK',
    timezone: 'America/New_York',
    utcOffsetMinutes: -300,
    description: 'The city that never sleeps. A global hub of finance, culture, and innovation.',
    gradient: 'from-slate-700 via-blue-600 to-indigo-700',
    image: '/images/cities/nyc.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1793878209/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793897151/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793872300/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793897126/original.jpg'
    ]
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    latitude: 37.57,
    longitude: 126.98,
    icao: 'RKSI',
    timezone: 'Asia/Seoul',
    utcOffsetMinutes: 540,
    description: 'Where ancient palaces meet cutting-edge technology. A dynamic blend of tradition and futurism.',
    gradient: 'from-violet-600 via-purple-500 to-fuchsia-600',
    image: '/images/cities/seoul.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1608954944/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1701618298/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1647579305/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1685571630/original.jpg'
    ]
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    latitude: 35.68,
    longitude: 139.69,
    icao: 'RJTT',
    timezone: 'Asia/Tokyo',
    utcOffsetMinutes: 540,
    description: 'A megacity where ancient temples stand alongside neon-lit skyscrapers.',
    gradient: 'from-rose-600 via-pink-500 to-violet-600',
    image: '/images/cities/tokyo.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1567938478/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1647579411/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1570808041/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1658398652/original.jpg'
    ]
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    country: 'China',
    latitude: 31.23,
    longitude: 121.47,
    icao: 'ZSPD',
    timezone: 'Asia/Shanghai',
    utcOffsetMinutes: 480,
    description: 'China\'s largest city. A global financial hub where East meets West.',
    gradient: 'from-rose-500 via-pink-500 to-fuchsia-600',
    image: '/images/cities/shanghai.jpg',
    webcams: [
      {
        type: 'link',
        url: 'https://www.skylinewebcams.com/zh/webcam/china/shanghai/shanghai/skyline-of-shanghai.html',
      },
    ],
    moji: 'https://tianqi.moji.com/weather/china/shanghai/shanghai'
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    latitude: 1.29,
    longitude: 103.85,
    icao: 'WSSS',
    timezone: 'Asia/Singapore',
    utcOffsetMinutes: 480,
    description: 'A global financial hub where cultures converge. Gardens, skyscrapers, and world-class cuisine.',
    gradient: 'from-emerald-600 via-teal-500 to-cyan-600',
    image: '/images/cities/singapore.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1369190454/original.jpg'
    ]
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    country: 'India',
    latitude: 26.85,
    longitude: 80.95,
    icao: 'VILK',
    timezone: 'Asia/Kolkata',
    utcOffsetMinutes: 330,
    description: 'City of Nawabs. Mughal heritage, kebabs, and the heart of Uttar Pradesh.',
    gradient: 'from-amber-600 via-orange-500 to-rose-600',
    image: '/images/cities/lucknow.jpg',
  },
  {
    id: 'tel-aviv',
    name: 'Tel Aviv',
    country: 'Israel',
    latitude: 32.09,
    longitude: 34.78,
    icao: 'LLBG',
    timezone: 'Asia/Jerusalem',
    utcOffsetMinutes: 120,
    description: 'The White City. Mediterranean beaches, Bauhaus architecture, and a thriving tech scene.',
    gradient: 'from-sky-500 via-blue-500 to-indigo-600',
    image: '/images/cities/tel-aviv.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1748254982/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793900793/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793900794/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1639421838/original.jpg'

    ]
  },
  {
    id: 'wellington',
    name: 'Wellington',
    country: 'New Zealand',
    latitude: -41.29,
    longitude: 174.78,
    icao: 'NZWN',
    timezone: 'Pacific/Auckland',
    utcOffsetMinutes: 720,
    description: 'The capital of New Zealand. Windy hills, craft beer, and film culture.',
    gradient: 'from-slate-600 via-blue-600 to-indigo-700',
    image: '/images/cities/wellington.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1533848823/original.jpg',

    ]
  },
  {
    id: 'atlanta',
    name: 'Atlanta',
    country: 'USA',
    latitude: 33.64,
    longitude: -84.43,
    icao: 'KATL',
    timezone: 'America/New_York',
    utcOffsetMinutes: -300,
    description: 'The capital of the South. Birthplace of civil rights and home to the world\'s busiest airport.',
    gradient: 'from-emerald-600 via-teal-500 to-cyan-600',
    image: '/images/cities/atlanta.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1755892004/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1755898629/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793873553/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793873555/original.jpg',
    ],
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    latitude: 43.65,
    longitude: -79.38,
    icao: 'CYYZ',
    timezone: 'America/Toronto',
    utcOffsetMinutes: -300,
    description: 'Canada\'s largest city. A diverse, multicultural metropolis by the Great Lakes.',
    gradient: 'from-red-600 via-rose-500 to-pink-600',
    image: '/images/cities/toronto.jpg',
  },
  {
    id: 'london',
    name: 'London',
    country: 'UK',
    latitude: 51.51,
    longitude: -0.13,
    icao: 'EGLC',
    timezone: 'Europe/London',
    utcOffsetMinutes: 0,
    description: 'A historic capital spanning two millennia. Royal palaces, world-class museums, and global finance.',
    gradient: 'from-slate-800 via-blue-800 to-slate-700',
    image: '/images/cities/london.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1508415526/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1508413710/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793884687/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1624953543/original.jpg'
    ]
  },
  {
    id: 'lagos',
    name: 'Lagos',
    country: 'Nigeria',
    latitude: 6.52,
    longitude: 3.38,
    icao: 'DNMM',
    timezone: 'Africa/Lagos',
    utcOffsetMinutes: 60,
    description: 'Nigeria\'s largest city. Atlantic coastline, vibrant markets, and nonstop urban energy.',
    gradient: 'from-emerald-700 via-green-600 to-lime-600',
    image: '/images/cities/lagos.jpg',
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    latitude: -33.92,
    longitude: 18.42,
    icao: 'FACT',
    timezone: 'Africa/Johannesburg',
    utcOffsetMinutes: 120,
    description: 'South Africa\'s coastal jewel. Table Mountain, Atlantic winds, and dramatic ocean views.',
    gradient: 'from-cyan-600 via-blue-600 to-indigo-700',
    image: '/images/cities/cape-town.jpg',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    latitude: 48.86,
    longitude: 2.35,
    icao: 'LFPG',
    timezone: 'Europe/Paris',
    utcOffsetMinutes: 60,
    description: 'The City of Light. Art, fashion, gastronomy, and culture at the heart of Europe.',
    gradient: 'from-rose-600 via-pink-500 to-indigo-600',
    image: '/images/cities/paris.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1706118429/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1721599175/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1207755799/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1758303408/original.jpg',
    ],
  },
  {
    id: 'munich',
    name: 'Munich',
    country: 'Germany',
    latitude: 48.14,
    longitude: 11.58,
    icao: 'EDDM',
    timezone: 'Europe/Berlin',
    utcOffsetMinutes: 60,
    description: 'Bavarian capital. Beer gardens, Oktoberfest, and Alpine charm at the heart of Europe.',
    gradient: 'from-amber-600 via-yellow-500 to-amber-500',
    image: '/images/cities/munich.jpg',
  },
  {
    id: 'milan',
    name: 'Milan',
    country: 'Italy',
    latitude: 45.46,
    longitude: 9.19,
    icao: 'LIMC',
    timezone: 'Europe/Rome',
    utcOffsetMinutes: 60,
    description: 'Italy\'s fashion and finance capital. Gothic spires, design culture, and aperitivo evenings.',
    gradient: 'from-rose-600 via-red-500 to-orange-500',
    image: '/images/cities/milan.jpg',
  },
  {
    id: 'warsaw',
    name: 'Warsaw',
    country: 'Poland',
    latitude: 52.23,
    longitude: 21.01,
    icao: 'EPWA',
    timezone: 'Europe/Warsaw',
    utcOffsetMinutes: 60,
    description: 'Phoenix city. Rebuilt from ashes, where historic Old Town meets modern skyscrapers.',
    gradient: 'from-slate-700 via-red-600 to-rose-600',
    image: '/images/cities/warsaw.jpg',
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    latitude: 40.42,
    longitude: -3.70,
    icao: 'LEMD',
    timezone: 'Europe/Madrid',
    utcOffsetMinutes: 60,
    description: 'Capital of Spain. Royal palaces, tapas, and the soul of Iberian culture.',
    gradient: 'from-amber-600 via-red-500 to-rose-600',
    image: '/images/cities/madrid.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1750252930/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1478182529/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1703440221/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1793896752/original.jpg'
    ]
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'USA',
    latitude: 25.79,
    longitude: -80.29,
    icao: 'KMIA',
    timezone: 'America/New_York',
    utcOffsetMinutes: -300,
    description: 'Gateway to the Americas. Beaches, art deco, and Latin culture.',
    gradient: 'from-sky-500 via-cyan-500 to-teal-600',
    image: '/images/cities/miami.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1642561701/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1736342847/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1621689267/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1588249493/original.jpg'
    ]
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    latitude: 19.43,
    longitude: -99.13,
    icao: 'MMMX',
    timezone: 'America/Mexico_City',
    utcOffsetMinutes: -360,
    description: 'High-altitude capital of Mexico. Historic plazas, modern districts, and vibrant street life.',
    gradient: 'from-emerald-600 via-teal-600 to-cyan-700',
    image: '/images/cities/mexico-city.jpg',
  },
  {
    id: 'chicago',
    name: 'Chicago',
    country: 'USA',
    latitude: 41.98,
    longitude: -87.91,
    icao: 'KORD',
    timezone: 'America/Chicago',
    utcOffsetMinutes: -360,
    description: 'The Windy City. Architecture, deep-dish pizza, and blues.',
    gradient: 'from-slate-600 via-blue-700 to-indigo-800',
    image: '/images/cities/chicago.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1499764260/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1624255665/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1643653572/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1624250933/original.jpg'
    ]
  },
  {
    id: 'seattle',
    name: 'Seattle',
    country: 'USA',
    latitude: 47.45,
    longitude: -122.31,
    icao: 'KSEA',
    timezone: 'America/Los_Angeles',
    utcOffsetMinutes: -480,
    description: 'The Emerald City. Tech hub, coffee culture, and Pacific Northwest beauty.',
    gradient: 'from-emerald-700 via-green-600 to-teal-700',
    image: '/images/cities/seattle.jpg',
  },
  {
    id: 'ankara',
    name: 'Ankara',
    country: 'Turkey',
    latitude: 39.93,
    longitude: 32.86,
    icao: 'LTAC',
    timezone: 'Europe/Istanbul',
    utcOffsetMinutes: 180,
    description: 'Capital of Turkey. Ancient Anatolia meets modern government.',
    gradient: 'from-amber-700 via-orange-600 to-red-600',
    image: '/images/cities/ankara.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1759873524/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1760176982/original.jpg',
    ]
  },
  {
    id: 'dallas',
    name: 'Dallas',
    country: 'USA',
    latitude: 32.90,
    longitude: -97.04,
    icao: 'KDFW',
    timezone: 'America/Chicago',
    utcOffsetMinutes: -360,
    description: 'Big D. Oil, tech, and the heart of North Texas.',
    gradient: 'from-slate-500 via-blue-600 to-indigo-600',
    image: '/images/cities/dallas.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1666664505/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1666641464/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1693849189/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1666648673/original.jpg'
    ]
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    latitude: -34.82,
    longitude: -58.54,
    icao: 'SAEZ',
    timezone: 'America/Argentina/Buenos_Aires',
    utcOffsetMinutes: -180,
    description: 'Paris of South America. Tango, steak, and European elegance.',
    gradient: 'from-sky-600 via-blue-500 to-indigo-600',
    image: '/images/cities/buenos-aires.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1735938641/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1579385444/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1751040831/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1691337947/original.jpg',
    ],
  },
  {
    id: 'chengdu',
    name: 'Chengdu',
    country: 'China',
    latitude: 30.67,
    longitude: 104.07,
    icao: 'ZUUU',
    timezone: 'Asia/Shanghai',
    utcOffsetMinutes: 480,
    description: 'Land of abundance. Spicy Sichuan cuisine, teahouses, and giant pandas.',
    gradient: 'from-rose-700 via-red-600 to-amber-600',
    image: '/images/cities/chengdu.jpg',
    moji: 'https://tianqi.moji.com/weather/china/sichuan/chengdu'
  },
  {
    id: 'chongqing',
    name: 'Chongqing',
    country: 'China',
    latitude: 29.56,
    longitude: 106.55,
    icao: 'ZUCK',
    timezone: 'Asia/Shanghai',
    utcOffsetMinutes: 480,
    description: 'Mountain city. Hot pot, foggy Yangtze gorges, and dramatic night skylines.',
    gradient: 'from-orange-700 via-amber-600 to-yellow-600',
    image: '/images/cities/chongqing.jpg',
    moji: 'https://tianqi.moji.com/weather/china/chongqing/chongqing'
  },
  {
    id: 'wuhan',
    name: 'Wuhan',
    country: 'China',
    latitude: 30.59,
    longitude: 114.31,
    icao: 'ZHHH',
    timezone: 'Asia/Shanghai',
    utcOffsetMinutes: 480,
    description: 'Nine provinces thoroughfare. Rivers, bridges, and central China energy.',
    gradient: 'from-cyan-700 via-blue-600 to-indigo-700',
    image: '/images/cities/wuhan.jpg',
    moji: 'https://tianqi.moji.com/weather/china/hubei/wuhan'
  },
  {
    id: 'shenzhen',
    name: 'Shenzhen',
    country: 'China',
    latitude: 22.54,
    longitude: 114.06,
    icao: 'ZGSZ',
    timezone: 'Asia/Shanghai',
    utcOffsetMinutes: 480,
    description: 'Innovation hub. Futuristic towers, maker culture, and Pearl River Delta pace.',
    gradient: 'from-violet-700 via-purple-600 to-fuchsia-600',
    image: '/images/cities/shenzhen.jpg',
    moji: 'https://tianqi.moji.com/weather/china/guangdong/shenzhen'
  },
  {
    id: 'beijing',
    name: 'Beijing',
    country: 'China',
    latitude: 39.90,
    longitude: 116.41,
    icao: 'ZBAA',
    timezone: 'Asia/Shanghai',
    utcOffsetMinutes: 480,
    description: 'Northern capital. Imperial heritage, hutongs, and the pulse of modern China.',
    gradient: 'from-red-800 via-rose-700 to-amber-700',
    image: '/images/cities/beijing.jpg',
    moji: 'https://tianqi.moji.com/weather/china/beijing/beijing'
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    country: 'China',
    latitude: 22.32,
    longitude: 114.17,
    icao: 'VHHH',
    timezone: 'Asia/Hong_Kong',
    utcOffsetMinutes: 480,
    description: 'Harbor city of peaks and towers. Dim sum, neon alleys, and Victoria Peak views.',
    gradient: 'from-amber-500 via-orange-500 to-rose-600',
    image: '/images/cities/hong-kong.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1166267733/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1526831849/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1592304269/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1627525317/original.jpg',
    ],
    moji: 'https://tianqi.moji.com/weather/china/hong-kong/hong-kong-island-',
  },
  {
    id: 'taipei',
    name: 'Taipei',
    country: 'China',
    latitude: 25.03,
    longitude: 121.56,
    icao: 'RCTP',
    timezone: 'Asia/Taipei',
    utcOffsetMinutes: 480,
    description: 'Basin capital. Night markets, hot springs, and Taipei 101 above subtropical hills.',
    gradient: 'from-emerald-700 via-teal-600 to-cyan-600',
    image: '/images/cities/taipei.jpg',
    webcams: [
      'https://imgproxy.windy.com/_/full/plain/current/1670717172/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1714903358/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1729755408/original.jpg',
      'https://imgproxy.windy.com/_/full/plain/current/1671974554/original.jpg',
    ],

  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    country: 'USA',
    latitude: 34.05,
    longitude: -118.24,
    icao: 'KLAX',
    timezone: 'America/Los_Angeles',
    utcOffsetMinutes: -480,
    description: 'City of Angels. Pacific beaches, film industry, and sprawling creative energy.',
    gradient: 'from-orange-500 via-amber-500 to-rose-600',
    image: '/images/cities/los-angeles.jpg',
  },
  {
    id: 'denver',
    name: 'Denver',
    country: 'USA',
    latitude: 39.74,
    longitude: -104.99,
    icao: 'KDEN',
    timezone: 'America/Denver',
    utcOffsetMinutes: -420,
    description: 'Mile High City. Rockies gateway, craft beer, and big-sky sunsets.',
    gradient: 'from-sky-600 via-blue-600 to-indigo-700',
    image: '/images/cities/denver.jpg',
  },
  {
    id: 'houston',
    name: 'Houston',
    country: 'USA',
    latitude: 29.76,
    longitude: -95.37,
    icao: 'KIAH',
    timezone: 'America/Chicago',
    utcOffsetMinutes: -360,
    description: 'Space City. Energy capital, NASA, and Gulf Coast diversity.',
    gradient: 'from-slate-600 via-teal-600 to-emerald-700',
    image: '/images/cities/houston.jpg',
  },
  {
    id: 'helsinki',
    name: 'Helsinki',
    country: 'Finland',
    latitude: 60.17,
    longitude: 24.94,
    icao: 'EFHK',
    timezone: 'Europe/Helsinki',
    utcOffsetMinutes: 120,
    description: 'Nordic capital by the Baltic. Design, saunas, and archipelago light.',
    gradient: 'from-cyan-700 via-sky-600 to-indigo-700',
    image: '/images/cities/helsinki.jpg',
  },
  {
    id: 'austin',
    name: 'Austin',
    country: 'USA',
    latitude: 30.27,
    longitude: -97.74,
    icao: 'KAUS',
    timezone: 'America/Chicago',
    utcOffsetMinutes: -360,
    description: 'Live music capital. Tech, tacos, and Hill Country cool.',
    gradient: 'from-violet-600 via-fuchsia-600 to-pink-600',
    image: '/images/cities/austin.jpg',
  },
  {
    id: 'moscow',
    name: 'Moscow',
    country: 'Russia',
    latitude: 55.76,
    longitude: 37.62,
    icao: 'UUEE',
    timezone: 'Europe/Moscow',
    utcOffsetMinutes: 180,
    description: 'Historic heart of Russia. Kremlin domes, metro palaces, and Volga-bound ambition.',
    gradient: 'from-red-800 via-rose-700 to-amber-800',
    image: '/images/cities/moscow.jpg',
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    latitude: 52.37,
    longitude: 4.90,
    icao: 'EHAM',
    timezone: 'Europe/Amsterdam',
    utcOffsetMinutes: 60,
    description: 'Canal-ring capital. Bikes, museums, and North Sea trading heritage.',
    gradient: 'from-orange-600 via-amber-500 to-yellow-500',
    image: '/images/cities/amsterdam.jpg',
  },
  {
    id: 'busan',
    name: 'Busan',
    country: 'South Korea',
    latitude: 35.18,
    longitude: 129.08,
    icao: 'RKPK',
    timezone: 'Asia/Seoul',
    utcOffsetMinutes: 540,
    description: 'Port city on the sea. Beaches, seafood markets, and film festivals.',
    gradient: 'from-blue-600 via-cyan-500 to-teal-600',
    image: '/images/cities/busan.jpg',
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    latitude: -6.21,
    longitude: 106.85,
    icao: 'WIII',
    timezone: 'Asia/Jakarta',
    utcOffsetMinutes: 420,
    description: 'Megacity on Java. Islands of culture amid tropical bustle.',
    gradient: 'from-emerald-700 via-green-600 to-lime-600',
    image: '/images/cities/jakarta.jpg',
  },
  {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    latitude: 3.15,
    longitude: 101.71,
    icao: 'WMKK',
    timezone: 'Asia/Kuala_Lumpur',
    utcOffsetMinutes: 480,
    description: 'Twin towers and rainforest fringe. Malay, Chinese, and Indian flavors.',
    gradient: 'from-teal-600 via-emerald-500 to-green-600',
    image: '/images/cities/kuala-lumpur.jpg',
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    latitude: 41.01,
    longitude: 28.98,
    icao: 'LTFM',
    timezone: 'Europe/Istanbul',
    utcOffsetMinutes: 180,
    description: 'Where continents meet. Bosphorus bridges, bazaars, and millennia of empires.',
    gradient: 'from-amber-700 via-orange-600 to-rose-700',
    image: '/images/cities/istanbul.jpg',
  },
  {
    id: 'jeddah',
    name: 'Jeddah',
    country: 'Saudi Arabia',
    latitude: 21.49,
    longitude: 39.19,
    icao: 'OEJN',
    timezone: 'Asia/Riyadh',
    utcOffsetMinutes: 180,
    description: 'Red Sea gateway of Saudi Arabia. Historic Al-Balad, modern waterfront, and desert maritime climate.',
    gradient: 'from-amber-600 via-orange-500 to-red-600',
    image: '/images/cities/jeddah.jpg',
  },
  {
    id: 'panama-city',
    name: 'Panama City',
    country: 'Panama',
    latitude: 8.98,
    longitude: -79.52,
    icao: 'MPTO',
    timezone: 'America/Panama',
    utcOffsetMinutes: -300,
    description: 'Canal crossroads of the Americas. Tropical skyline, maritime trade, and Caribbean-Pacific gateway.',
    gradient: 'from-cyan-600 via-sky-600 to-blue-700',
    image: '/images/cities/panama-city.jpg',
  },
]

/** Hemisphere for meteorology (wind/synoptic): equator (0°) counts as Northern. */
export function getCityHemisphere(latitude: number): 'north' | 'south' {
  return latitude < 0 ? 'south' : 'north'
}
